### ISSUE TITLE
ImportError: No module named 'osgeo'

### ISSUE THREAD

**Issue by hungtranm18** [LarsSchy/SMAC-M#20]
Hi team,

I'm getting the below error message while running "python3 bin/generate_shapefiles.py configfile.toml" command to convert S-57 dataset. 
```
  File "generate_light_sector.py", line 15, in <module>
    from osgeo import ogr
ImportError: No module named 'osgeo'
```
Some information about my environment:
```
OS: Ubuntu 18.04.2 LTS (OSGeoLive 12.0)
GDAL: GDAL 2.4.0, released 2018/12/14
pip: pip3 --version
pip 19.0.3 from /root/.local/share/virtualenvs/SMAC-M-BqzJCxzX/lib/python3.5/site-packages/pip (python 3.5)
```

Could you please help me to resolve this issue? Or can you tell more clearly about the steps to prepare the running environment? E.g: Should I build GDAL/OGR from source or just install it by apt-get command? Because when I run 2 below commands, the results are the same:
```
(SMAC-M) root@osgeolive:/home/user/SMAC-M# ogrinfo shp_s57data/ENC_ROOT/VN100001.000 
INFO: Open of `shp_s57data/ENC_ROOT/VN100001.000'
      using driver `S57' successful.
1: DSID (None)
2: Point (Point)
3: Line (Line String)
4: Area (Polygon)
5: Meta (None)
(SMAC-M) root@osgeolive:/home/user/SMAC-M# ogrinfo --config S57_PROFILE iw -ro shp_s57data/ENC_ROOT/VN100001.000 
INFO: Open of `shp_s57data/ENC_ROOT/VN100001.000'
      using driver `S57' successful.
1: DSID (None)
2: Point (Point)
3: Line (Line String)
4: Area (Polygon)
5: Meta (None)
```
I tried many other ENC files but the results were unchanged.

Thank you very much

**Comment by MarekBak** [comment]
Hello hungtranm18,

All is on main page. From what i remember to run: |ogrinfo --config 
S57_PROFILE iw ... you actually need to:|
|$ ogrinfo --version||
|
|GDAL 2.2.2, released ...||
|
|$ find / -name s57objectclasses.csv|
|||# You may have different path|
|||/usr/share/gdal/2.2/s57objectclasses.csv |

|$ wget 
https://raw.githubusercontent.com/OpenCPN/OpenCPN/master/data/s57data/s57objectclasses.csv 
$ wget 
https://raw.githubusercontent.com/OpenCPN/OpenCPN/master/data/s57data/s57attributes.csv 
# The path returned by find $ cp s57objectclasses.csv 
/usr/share/gdal/2.2/s57objectclasses_iw.csv /*# !!! Note on main page 
there is small typo below (both files MUST be _iw to make S57_PROFILE iw 
works)*/ $ cp s57attributes.csv 
/usr/share/gdal/2.2/||s57attributes_iw.csv And about osgeo. I guess 
you've missed part from that step from main page: */Prepare the Pipenv 
Virtual Environment/**(cross check all 3 steps from that point*||*||)||.*|

Regards,
Marek

||||


W dniu 2019-04-24 o 20:59, hungtranm18 pisze:

**Comment by hungtranm18** [comment]
Hi Marek,

Thanks for your quick reply. I have already run those steps but I still get this issue.
Step 1: Download s57objectclasses.csv and s57attributes.csv from OpenCPN source. Then copy them into 
/usr/share/gdal/2.2/ with the new name
```
root@osgeolive:/home/user/SMAC-M# cp s57objectclasses.csv /usr/share/gdal/2.2/s57objectclasses_iw.csv
root@osgeolive:/home/user/SMAC-M# cp s57attributes.csv /usr/share/gdal/2.2/s57attributes_iw.csv
root@osgeolive:/home/user/SMAC-M# ogrinfo --config S57_PROFILE iw -ro shp_s57data/ENC_ROOT/VN100001.000 
INFO: Open of `shp_s57data/ENC_ROOT/VN100001.000'
      using driver `S57' successful.
1: DSID (None)
2: Point (Point)
3: Line (Line String)
4: Area (Polygon)
5: Meta (None)
root@osgeolive:/home/user/SMAC-M# ogrinfo --config S57_PROFILE iw -ro shp_s57data/ENC_ROOT/VN400006.000 
INFO: Open of `shp_s57data/ENC_ROOT/VN400006.000'
      using driver `S57' successful.
1: DSID (None)
2: Point (Point)
3: Line (Line String)
4: Area (Polygon)
5: Meta (None)
```
Step 2: Prepare the pipenv virtual environment
I got some errors while run pipenv run pip install "GDAL<=$(gdal-config --version)"
```
root@osgeolive:/home/user/SMAC-M# pipenv install
Installing dependencies from Pipfile.lock (2c50b6)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 3/3 — 00:00:02
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.

root@osgeolive:/home/user/SMAC-M# pipenv run pip install "GDAL<=$(gdal-config --version)"
Loading .env environment variables...
Collecting GDAL<=2.4.0
  Using cached https://files.pythonhosted.org/packages/7c/b0/a2ecb10a68a319910c4681f452c83843b99c4ef6231d33a8e55b0104a50c/GDAL-2.4.0.tar.gz
Building wheels for collected packages: GDAL
  Building wheel for GDAL (setup.py) ... error
.....
extensions/gdal_wrap.cpp:173:11: fatal error: Python.h: No such file or directory
```
I have installed some packages: python-dev, python3-dev, ... but I don't know what I installed missing something.

Thanks,

**Comment by alexbrault** [comment]
Hello, @hungtranm18 

Could you show me the output of `dpkg -l python3-dev`

**Comment by hungtranm18** [comment]
Hi @alexbrault,

The output of your command is shown as below:
```
root@osgeolive:/home/user/SMAC-M# dpkg -l python3-dev
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                              Version               Architecture          Description
+++-=================================-=====================-=====================-=======================================================================
ii  python3-dev                       3.6.7-1~18.04         amd64                 header files and a static library for Python (default)

```

Thanks

**Comment by alexbrault** [comment]
Alright, it seems you have python headers installed. Have you tried installing the GDAL python package again after installing python3-dev?

If not that, the problem may be due to the mismatch between your python headers version (3.6.7) and the python used within the virtual environment (3.5.x), although in that case, I'd expect a different error than "Python.h: No such file or directory"

**Comment by MarekBak** [comment]
At start I was using windows 10 + ubuntu. So it should work without problems. Here's more or less mine env (as pointed above I've changed python in Pipfile):
`
(SMAC-M-master) arni@PC10531:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

(SMAC-M-master) arni@PC10531:~$ history | grep apt-get
   21  sudo apt-get install python
   22  sudo apt-get install pip
   23  sudo apt-get install python-setuptools python-dev build-essential
   24  sudo apt-get update
   25  sudo apt-get install python-setuptools python-dev build-essential
   28  sudo apt-get install python-pip
  572  sudo apt-get install imagemagick

(SMAC-M-master) arni@PC10531:~$ ogrinfo --version
GDAL 2.2.3, released 2017/11/20

(SMAC-M-master) arni@PC10531:~$ ls -l /usr/share/gdal/
total 0
drwxr-xr-x 1 root root 4096 Mar 13 12:15 2.2

(SMAC-M-master) arni@PC10531:~$ ls -l /usr/share/gdal/2.2/*iw*
-rw-r--r-- 1 root root 12310 Mar 13 10:38 /usr/share/gdal/2.2/s57attributes_iw.csv
-rw-r--r-- 1 root root 41998 Mar 13 12:07 /usr/share/gdal/2.2/s57objectclasses_iw.csv

(SMAC-M-master) arni@PC10531:~$ ogrinfo --config S57_PROFILE iw -ro DE110000.000
INFO: Open of `DE110000.000'
      using driver `S57' successful.
1: DSID (None)
2: ADMARE (Polygon)
3: BRIDGE
4: BUISGL
5: BUAARE
6: CANALS
7: COALNE
8: CONZNE (Polygon)
9: DWRTPT (Polygon)
10: DEPARE
11: DEPCNT
12: EXEZNE (Polygon)
13: ISTZNE (Polygon)
14: LAKARE (Polygon)
15: LNDARE
16: LNDRGN
17: LNDMRK
18: LIGHTS (Point)
19: MAGVAR
20: PILPNT (Point)
21: PRCARE
22: RCRTCL
23: RIVERS
24: SEAARE
25: SLCONS
26: SOUNDG (3D Multi Point)
27: TESARE (Polygon)
28: TSELNE
29: TSSBND
30: TSSLPT (Polygon)
31: TSSRON (Polygon)
32: TSEZNE (Polygon)
33: TWRTPT (Polygon)
34: M_COVR (Polygon)
35: M_NSYS (Polygon)
36: M_QUAL (Polygon)

(SMAC-M-master) arni@PC10531:~$ cat s57/SMAC-M-master/Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]
"autopep8" = "*"
"flake8" = "*"

[packages]
numpy = "*"
wand = "*"
toml = "*"

[requires]
python_version = "3.6"
`

**Comment by hungtranm18** [comment]
Hi @alexbrault @MarekBak , thanh you very much for your help. I have reinstalled by below command
```
sudo python -m pip uninstall pip && sudo apt install python-pip --reinstall
sudo python3 -m pip uninstall pip && sudo apt install python3-pip --reinstall
```
Now it works well for me.
Thanks,
