### ISSUE TITLE
Blank Map

### ISSUE THREAD

**Issue by teriterance** [LarsSchy/SMAC-M#26]
**My configuration**
OS : ubuntu 18.04
GDAL: 2.4.2, released 2019/06/28
MapServer: 7.0.7

Link
http://localhost/cgi-bin/mapserv?map=/home/noaa_enc/map/SeaChart_DAY_BRIGHT.map&SERVICE=WMS&REQUEST=Getmap&VERSION=1.1.1&LAYERS=SeaChart_DAY_BRIGHT&srs=EPSG:4326&BBOX=133870,5798110,1541520,7459340&FORMAT=application/openlayers&WIDTH=2000&HEIGHT=1100

**on my config I tried to run your script but in the end I got a blank page**

**Comment by juliensam** [comment]
Hello,

Thank you for your interest.
We will need a bit more details.
What command did you ran?
What was the output?
Is there any layers created in the resulting mapfiles?

**Comment by teriterance** [comment]
the command 
```
cd ../SMAC-M
python3 bin/generate_toml_config.py \
          --chart ../noaa_enc/ENC_ROOT \
          -rule-default-color IHO \
          --chartsymbols ./chart-installation/generate_map_files/resources/chartsymbols/chartsymbols_S57.xml \
          -enhancedchartdata ../noaa_enc/shp \
          --tablename Paper \
          --displaycategory Standard \
          --rule-set-path ./chart-installation/generate_map_files/resources/rules/ \
          -o configfile.toml
```
give me as outpu many line like that

```
+ ogr2ogr -append -skipfailures -f 'ESRI Shapefile' --config S57_PROFILE iw /home/gabin/swail/noaa_enc/shp/3/CL3_resare_lcase_POLYGON.shp -where PRIM=3 /home/gabin/swail/noaa_enc/ENC_ROOT/US3EC11M/US3EC11M.000 resare
+ ogr2ogr -append -skipfailures -f 'ESRI Shapefile' --config S57_PROFILE iw /home/gabin/swail/noaa_enc/shp/3/CL3_topmar_lcase_POINT.shp -where PRIM=1 /home/gabin/swail/noaa_enc/ENC_ROOT/US3EC11M/US3EC11M.000 topmar
```

the command 
```
python3 ../bin/generate_shapefiles.py config.enc.noaa.toml
```
give me this output
```

python3 ../chart-installation/generate_map_files/generate_map_config.py config.enc.noaa.toml
Existing color tables found at /home/gabin/swail/SMAC-M/chart-installation/generate_map_files/resources/rules/color_tables
Existing layers found in /home/gabin/swail/SMAC-M/chart-installation/generate_map_files/resources/rules/layer_rules
/home/gabin/swail/SMAC-M/chart-installation/generate_map_files/mapgen/symbol.py:412: UserWarning: Pattern command not implemented: CI
  warnings.warn('Pattern command not implemented: ' + command)
Check geometry of all layers...
Loading DAY_WHITEBACK.csvON.shp                            
Loading NIGHT.csv
Loading DAY_BLACKBACK.csv
Loading DUSK.csv
Loading DAY_BRIGHT.csv
/home/gabin/swail/SMAC-M/chart-installation/generate_map_files/mapgen/symbol.py:412: UserWarning: Pattern command not implemented: CI
  warnings.warn('Pattern command not implemented: ' + command)
```

I am getting many layers in resulting map file ( there are 6 layer I thing )

**Comment by teriterance** [comment]
@juliensam I tried this code on a virtual machine with the same configuration as yours (ubuntu 16.04) to finally get the same result, a white image.
I also tried to open the file maps with qgis and I get an error on the layers.

**Comment by juliensam** [comment]
Is it possible for you to share a sample dataset?

**Comment by teriterance** [comment]
yes at this link wget https://www.charts.noaa.gov/ENCs/All_ENCs.zip
in fact I used the documentation that is provided for the NOAA charts

**Comment by teriterance** [comment]
in fact I used the documentation that is provided for the NOAA charts

**Comment by teriterance** [comment]
you can get my map file at this link https://drive.google.com/file/d/1hivMS-Jlp81cCSLn4cu35lt7rKxhs_im/view?usp=sharing

**Comment by MarekBak** [comment]
Please check if the BBOX is correct both in term of location and zoom level.

**Comment by teriterance** [comment]
Yes it was a problem with my BBOX. I found this site who help to compute BBOX 
http://bboxfinder.com
